# Generated by Django 4.2.13 on 2024-07-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latest_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
