# Generated by Django 4.2.13 on 2024-07-03 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
